apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-application
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-application
  template:
    metadata:
      labels:
        app: example-application
    spec:
      containers:
      - image: sivabalan19/example-application:v2
        name: example-application
        ports:
        - containerPort: 8080
