apiVersion: v1
kind: Service
metadata:
  name: example-application
  namespace: default
  labels:
    app: example-application
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: example-application
