---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: applications
  namespace: default
spec:
  interval: 3s
  ref:
    branch: main
  url: ssh://git@github.com/sivabalan19/example-environment
